services:
  - type: web
    name: coach-entel-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false
